directories:
  output: release
  buildResources: build
appId: com.electron.app
productName: JARVIS
files:
  - filter:
      - dist/**/*
      - electron/**/*
mac:
  category: public.app-category.utilities
win:
  target: nsis
linux:
  target: AppImage
electronVersion: 28.3.3
